HellpDesk-ads (13.09.25)/Models/ContatoModel.cs
namespace ProjetoAula.Models
{
    public class ContatoModel
    {
        public  int id { get; set; }
        public string nome { get; set; }
        public int cpf { get; set; }
        public string email { get; set; }
    }
}

HellpDesk-ads (13.09.25)/Models/ErrorViewModel.cs
namespace ProjetoAula.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

HellpDesk-ads (13.09.25)/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using ProjetoAula.Models;

namespace ProjetoAula.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult home()
        {
            return View();
        }

        public IActionResult privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }

    public class LoginController : Controller
    {
        public IActionResult login()
        {
            return View();
        }
    }

    public class ContatoController : Controller
    {
        public IActionResult contato()
        {
            return View();
        }
    }

    public class CadastroController : Controller
    {
        public IActionResult cadastro()
        {
            return View();
        }
    }
}

HellpDesk-ads (13.09.25)/Views/Cadastro/cadastro.cshtml
@{
    ViewData["Title"] = "Cadastro";
}
<link rel="stylesheet" href="~/css/cadastro.css" />

<bodyCadastro>
    <div class="containe">

        <div class="form", >

            <form action="#">

                <div class="form-header">

                    <div class="title">
                        <h1>Cadastre-se</h1>
                    </div>

                    <div class="login-button">
                        <button><a href="#">Entrar</a></button>
                    </div>

                </div>

                <div class="input-group">

                    <div class="input-box">
                        <label for="firstname">Primeiro nome</label>
                        <input id="firstname" type="text" name="firstname" placeholder="Digite seu Primeiro nome" required>
                    </div>

                    <div class="input-box">
                        <label for="lastneme">Sobrenome</label>
                        <input id="lastneme" type="text" name="lastneme" placeholder="Digite seu sobrenome" required>
                    </div>

                    <div class="input-box">
                        <label for="email">E-mail</label>
                        <input id="email" type="text" name="email" placeholder="Digite seu e-mail" required>
                    </div>

                    <div class="input-box">
                        <label for="number">Celular</label>
                        <input id="number" type="text" name="number" placeholder="(XX) XXXX-XXXX" required>
                    </div>

                    <div class="input-box">
                        <label for="password">Senha</label>
                        <input id="password" type="text" name="password" placeholder="Digite sua senha" required>
                    </div>

                    <div class="input-box">
                        <label for="confirmepassword">Comfirme sua senha</label>
                        <input id="confirmepassword" type="text" name="confirmepassword" placeholder="Confirme sua senha" required>
                    </div>
                </div>

                <div class="gender-inputs">
                    <div class="gender-title">
                        <h6>Gênero</h6>
                    </div>

                    <div class="gender-group">
                        <div class="gender-inputs">
                            <input type="radio" id="female" name="gender">
                            <label for="female">Feminino</label>
                        </div>

                        <div class="gender-inputs">
                            <input type="radio" id="male" name="gender">
                            <label for="male">Masculino</label>
                        </div>

                        <div class="gender-inputs">
                            <input type="radio" id="others" name="gender">
                            <label for="others">Outros</label>
                        </div>

                        <div class="gender-inputs">
                            <input type="radio" id="none" name="gender">
                            <label for="none">Prefiro não dizer</label>
                        </div>
                    </div>
                </div>

                <div class="continue-button">
                    <button><a href="#">Contiuar</a></button>
                </div>
            </form>
        </div>
    </div>
</bodyCadastro>
</html>

HellpDesk-ads (13.09.25)/Views/Home/home.cshtml
@{
    ViewData["Title"] = "Home Page";
}


<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>

</div>

HellpDesk-ads (13.09.25)/Views/Login/login.cshtml
@{
	ViewData["Title"] = "Login";
}

<link rel="stylesheet" href="~/css/login.css" />
<bodyLogin>
	<div class="wrepper">
		<form action="">
			<h1>Login</h1>

			<div class="input-box">
				<input type="text" placeholder="Username" required>
				<i class='bx bxs-user'></i>
			</div>

			<div class="input-box">
				<input type="password" placeholder="Password" required>
				<i class='bx bxs-lock-alt'></i>
			</div>

			<div class="remember-forgot">
				<label><input type="checkbox"> Remember me</label>
				<a href="#">Forgot password?</a>
			</div>

			<button type="submit" class="btn">Login</button>

			<div class="register-link">
				<p>Don't have an acount? <a href="#">Register</a></p>
			</div>


		</form>

	</div>    
</bodyLogin>

HellpDesk-ads (13.09.25)/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HellpDesk</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProjetoAula.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="home">HellpDesk - ADS</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="home">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contato" asp-action="contato">Contato</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cadastro" asp-action="cadastro">Cadastro</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="privacy">Privacy</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - ProjetoAula - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

HellpDesk-ads (13.09.25)/Views/contato/contato.cshtml
@{
    ViewData["Title"] = "Contato";
}
<h1>oi</h1>